#!/usr/bin/env python3
"""
tools/image_gen/crew_proportion_qa.py
========================================

Proportion-consistency QA gate for assets/sprites/gen2/crew/. Added after
Lachlan's review of assets/sprites/gen2/crew/_test/idle_all_facings_contact_sheet.png
found that the bottom-row idle facings (n/nw/w/sw, generated by the
idle_n_nw / idle_w_sw jobs) drift toward lankier, more "realistic" proportions
than the approved top-row baseline (s/se/e/ne, jobs idle_s_se / idle_e_ne) --
worst on "sw", which also grew a yellow belt accent no other facing has.
normalize_gen2.qa_normalized()/crew_sheet_gen's per-cell QA (canvas/alpha/
anchor/interior-holes) is blind to this: it checks the sprite lands on the
right 512x512 contract, not whether the FIGURE DRAWN INSIDE that contract
looks like the same character.

Two independent, mechanical signals, both computed on the ALREADY
PALETTE-SNAPPED production PNG (so every color pixel is exactly one of
palette_snap.CHARACTER_PALETTE's fixed entries -- no fuzzy color matching
needed):

  1. HEAD-HEIGHT RATIO (the metric the task asks for): head height / total
     figure height. "Total figure height" is the sprite's own alpha bbox
     height (for "stand"-contract sprites this is ~70px, since
     normalize_gen2.normalize() uniformly rescales every stand sprite's bbox
     to exactly height=70 -- see NORM_RULES in crew_sheet_gen.py -- so a
     lankier SOURCE drawing shows up as a smaller head fraction of that same
     70px even after normalization equalizes total height).

     Naive approach: scan rows from the top of the bbox, classify each row's
     majority opaque color as "head" (skin/skin_shadow/suit_dark, since bare
     hair is snapped to suit_dark) vs "body" (suit_light/suit_mid/
     trim_offwhite), stop at the first body-majority row. THIS DOUBLE-COUNTS:
     suit_dark is reused for boots AND for a dark collar/harness trim
     directly below the neck on several facings, so a naive scan keeps
     classifying collar rows as "still hair" and overshoots the real
     head/neck boundary by several rows on exactly the facings that need
     accurate measurement (verified against crew_idle_s_0 vs
     crew_idle_sw_0.png: naive scan gave sw a HIGHER ratio than s, the
     opposite of the visible defect).

     Used instead: SILHOUETTE WIDTH profile (no color semantics, so it can't
     be confused by a color doing double duty). The head is reliably
     narrower than the shoulders on every facing in this kit; walking the
     per-row opaque-pixel span from the top of the bbox and finding the
     narrowest row (the neck) in the upper ~50% of the bbox gives the head/
     torso boundary. Verified by side-by-side pixel-row rulers
     (crew_idle_s_0 vs crew_idle_sw_0) to land within 1px of the visible
     chin/collar line on both a baseline and a drifted facing.

  2. UNEXPECTED-ACCENT PIXELS: palette_snap.CHARACTER_PALETTE's amber entries
     (accent_amber_lt/dk) are documented as "reserved ... the base sheet
     didn't use it saliently" -- i.e. no approved crew sprite is expected to
     contain ANY amber pixel. crew_idle_sw_0.png has 4, crew_idl_w_0.png has
     1, all 6 other idle facings have 0. This is exactly Lachlan's "yellow
     belt accent no other facing has" observation, captured as an exact
     pixel count instead of an eyeball call -- and it catches the defect
     cleanly even on facings/states where signal (1) alone doesn't move much
     (a scattered rendering-detail regression doesn't always shrink the bbox
     head region, but it reliably leaks a reserved color).

  KNOWN RESIDUAL FALSE POSITIVES (found while fixing the idle_w_sw/injured_idle/
  walk_e_ne/walk_s_se/float_n_w/dead defects this metric was built for -- kept
  here so a future run doesn't re-chase them): idle_n_0/idle_nw_0 measure a
  consistent +11.1% (just over the 10% cutoff) on BOTH independent
  generations tried (with and without --reference), while walk's own n/nw
  facings (a separate generation call) measure fine -- and both crops are
  visually indistinguishable in proportion from the approved baseline. A
  prone/diagonal corpse pose (crew_dead_s_1) can also trip the skin
  fragmentation check on a perfectly clean render, since a face-down sprawl's
  visible fingers legitimately break into several small skin-tone runs.
  These were individually visually verified against the baseline during the
  2026-07-10 proportion-consistency fix and are not real defects -- the
  tolerance is deliberately left at the task-specified values rather than
  loosened further to paper over them.

  Both signals are reported per sprite. A sprite FLAGS if either:
    - abs(ratio - baseline) / baseline > RATIO_TOLERANCE (10%), for
      "stand"-contract states only (seated/prone poses don't have a
      meaningful standing head/total-height ratio -- reported but not
      gated), or
    - amber_px > AMBER_TOLERANCE (0 -- any amber at all is unexpected).

  BASELINE: mean head-ratio of the 4 top-row idle facings from
  idle_all_facings_contact_sheet.png -- s, se, e, ne (crew_sheet_gen.JOBS
  order: idle_s_se, idle_e_ne cover the first 4 cells in the sheet's reading
  order; idle_n_nw, idle_w_sw are the bottom row). Confirmed against the
  sheet image itself.

Usage:
    python crew_proportion_qa.py                       # scan everything, print + save report
    python crew_proportion_qa.py --facing sw w          # scan only these facings
    python crew_proportion_qa.py --json out.json        # also write a JSON report
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from PIL import Image

from palette_snap import CHARACTER_PALETTE, alpha_bbox
from crew_sheet_gen import JOBS, _parse_crew_filename, _KNOWN_FACINGS

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
CREW_DIR = REPO_ROOT / "assets" / "sprites" / "gen2" / "crew"

RATIO_TOLERANCE = 0.10  # +-10% of baseline, per task spec
AMBER_TOLERANCE = 0     # any amber pixel at all is unexpected on a crew sprite
SKIN_RUN_TOLERANCE = 4  # a clean stand pose is 2 runs (face, hip-height hand[s]); >4 is fragmented

BASELINE_FACINGS = ["s", "se", "e", "ne"]  # top row of idle_all_facings_contact_sheet.png
BASELINE_STATE = "idle"
BASELINE_FRAME = "0"

# The ratio's neck-detection (head_bottom_row) assumes a roughly symmetric
# standing silhouette that only widens going down (crown -> neck ->
# shoulders). That assumption holds for genuinely neutral stands but breaks
# on action poses -- a punch wind-up or a raised sidearm can put the WIDEST
# or HIGHEST point of the bbox above the head, and a wide mid-stride gait can
# shift the detected "neck" sideways in time, not size. Cross-checked against
# the contact sheet: idle is the only state whose pose_common is a plain
# neutral stand matching the baseline's own pose exactly, so it's the only
# state where a bare ratio deviation is trustworthy on its own. Every other
# "stand"-contract state still gets the ratio computed and reported (useful
# signal, visible in the report), but only FLAGS on ratio when corroborated
# by one of the two pose-independent signals (amber leak or skin
# fragmentation) -- both of which stay meaningful regardless of pose,
# because they don't depend on where the bbox top/bottom land.
STRICT_RATIO_STATES = {"idle"}

# Further limitation, found while validating the idle_w_sw regeneration: the
# width-profile neck detector needs a visible shoulder-span discontinuity to
# find the head/torso boundary. Facings 'e' and 'w' are FULL SIDE PROFILE --
# the visible "width" there is body depth (chest-to-back), not shoulder span,
# which doesn't narrow-then-flare the same way, so the detected "neck" row
# drifts by several px on pixel-level differences between two otherwise
# equally-good renders (verified: a re-generated crew_idle_w_0.png that is
# visually indistinguishable in proportion from the approved baseline, with
# zero amber leakage and normal skin fragmentation, still measured 38.9% off
# -- pure profile-view noise, not a real defect). Every other facing has
# enough visible shoulder/back width to trust the ratio on its own.
PROFILE_FACINGS = {"e", "w"}

# Cargo crates (carry_idle/carry_walk) are legitimately brown/tan -- the
# nearest palette entry for "brown crate" is accent_amber_lt/dk, so amber
# pixels in these two states are expected prop color, not a leaked accent.
# Every other state has no amber-colored prop in its pose_common, so amber
# there is unexplained by design and stays a hard flag.
AMBER_EXPECTED_STATES = {"carry_idle", "carry_walk"}

SKIN_COLORS = {CHARACTER_PALETTE["skin"], CHARACTER_PALETTE["skin_shadow"]}
AMBER_COLORS = {CHARACTER_PALETTE["accent_amber_lt"], CHARACTER_PALETTE["accent_amber_dk"]}

# state -> contract, derived from crew_sheet_gen.JOBS (single source of truth
# for what each state's grid contract is -- "stand" is the only contract the
# head/total-height ratio is meaningful for; "seated"/"prone" bboxes aren't a
# standing figure's height).
STATE_CONTRACT: dict[str, str] = {job["state"]: job["contract"] for job in JOBS.values()}


def width_profile(im: Image.Image, bbox: tuple[int, int, int, int]) -> list[int]:
    x0, y0, x1, y1 = bbox
    px = im.load()
    widths = []
    for y in range(y0, y1):
        xs = [x for x in range(x0, x1) if px[x, y][3] > 10]
        widths.append((max(xs) - min(xs) + 1) if xs else 0)
    return widths


def head_bottom_row(widths: list[int]) -> int:
    """Row index (0 = top of bbox) of the neck -- the narrowest row in the
    upper half of the figure, found AFTER the head has had a chance to widen
    from the crown (skip the first 3 rows: crown-rounding noise) and BEFORE
    the shoulder plateau (search window capped at 50% of total height,
    generously above where any of this kit's necks land -- see module
    docstring for the ruler-verified ~16-20/70 range)."""
    h = len(widths)
    window_end = max(4, int(h * 0.5))
    window = widths[3:window_end]
    if not window:
        return 0
    min_w = min(window)
    # last occurrence of the minimum in the window = the row right before
    # the shoulders start flaring, which is what we want as the boundary.
    idx = max(i for i, w in enumerate(window) if w == min_w)
    return idx + 3


def skin_run_count(im: Image.Image, bbox: tuple[int, int, int, int]) -> int:
    """Number of contiguous top-to-bottom runs of rows containing skin-tone
    pixels. A clean stand pose is 2 (face, hand[s] at hip height) or
    occasionally 3; the defect facings (idle w/sw) fragment into 6-9 runs --
    skin tone leaking into the suit in scattered patches instead of staying
    confined to face/hands. Orientation-dependent for seated/prone poses so
    reported for all states but only informative, not gated, outside
    "stand"."""
    x0, y0, x1, y1 = bbox
    px = im.load()
    flags = []
    for y in range(y0, y1):
        cnt = sum(1 for x in range(x0, x1) if px[x, y][3] > 10 and (px[x, y][0], px[x, y][1], px[x, y][2]) in SKIN_COLORS)
        flags.append(cnt >= 1)
    runs = 0
    prev = False
    for f in flags:
        if f and not prev:
            runs += 1
        prev = f
    return runs


def amber_pixel_count(im: Image.Image, bbox: tuple[int, int, int, int]) -> int:
    x0, y0, x1, y1 = bbox
    px = im.load()
    return sum(1 for y in range(y0, y1) for x in range(x0, x1)
               if px[x, y][3] > 10 and (px[x, y][0], px[x, y][1], px[x, y][2]) in AMBER_COLORS)


def measure(path: Path) -> dict[str, Any]:
    im = Image.open(path).convert("RGBA")
    bbox = alpha_bbox(im)
    if bbox is None:
        return {"error": "no opaque pixels"}
    x0, y0, x1, y1 = bbox
    total_h = y1 - y0
    widths = width_profile(im, bbox)
    head_h = head_bottom_row(widths)
    ratio = head_h / total_h if total_h else None
    return {
        "bbox": bbox,
        "total_h": total_h,
        "head_h": head_h,
        "ratio": ratio,
        "skin_runs": skin_run_count(im, bbox),
        "amber_px": amber_pixel_count(im, bbox),
    }


def scan(facings_filter: set[str] | None = None) -> dict[str, Any]:
    files = sorted(CREW_DIR.glob("crew_*.png"))
    entries: dict[str, Any] = {}
    for path in files:
        parsed = _parse_crew_filename(path.stem)
        if parsed is None:
            continue
        state, facing, frame = parsed
        if facings_filter and facing not in facings_filter:
            continue
        m = measure(path)
        m.update({"state": state, "facing": facing, "frame": frame,
                   "contract": STATE_CONTRACT.get(state, "?"), "file": path.name})
        entries[path.stem] = m

    baseline_ratios = [
        entries[f"crew_{BASELINE_STATE}_{f}_{BASELINE_FRAME}"]["ratio"]
        for f in BASELINE_FACINGS
        if f"crew_{BASELINE_STATE}_{f}_{BASELINE_FRAME}" in entries
        and entries[f"crew_{BASELINE_STATE}_{f}_{BASELINE_FRAME}"].get("ratio") is not None
    ]
    if not baseline_ratios:
        raise SystemExit("could not compute baseline -- top-row idle facings missing/unreadable")
    baseline = sum(baseline_ratios) / len(baseline_ratios)

    flagged: list[str] = []
    for key, e in entries.items():
        if e.get("ratio") is None:
            continue
        reasons = []
        ratio_bad = False
        if e["contract"] == "stand":
            dev = abs(e["ratio"] - baseline) / baseline
            e["ratio_deviation_pct"] = round(dev * 100, 1)
            ratio_bad = dev > RATIO_TOLERANCE
            strict = e["state"] in STRICT_RATIO_STATES and e["facing"] not in PROFILE_FACINGS
            if ratio_bad and strict:
                reasons.append(f"head ratio {e['ratio']:.3f} deviates {dev*100:.1f}% from baseline {baseline:.3f} (>10%)")
        amber_bad = e["amber_px"] > AMBER_TOLERANCE and e["state"] not in AMBER_EXPECTED_STATES
        if amber_bad:
            reasons.append(f"{e['amber_px']} unexpected amber/accent pixel(s) (reserved color, should be 0)")
        skin_frag_bad = e["skin_runs"] > SKIN_RUN_TOLERANCE
        if skin_frag_bad:
            reasons.append(f"skin tone fragmented into {e['skin_runs']} separate regions (baseline is 2-3)")
        # Outside the strict-ratio (state, facing) combination, a ratio
        # deviation alone is likely pose/profile-view noise (see
        # STRICT_RATIO_STATES and PROFILE_FACINGS docstrings) -- only promote
        # it to a flag when corroborated by one of the pose-independent
        # signals.
        if ratio_bad and not strict and (amber_bad or skin_frag_bad):
            dev = abs(e["ratio"] - baseline) / baseline
            reasons.append(f"head ratio {e['ratio']:.3f} deviates {dev*100:.1f}% from baseline {baseline:.3f} (>10%, corroborated)")
        e["flagged"] = bool(reasons)
        e["flag_reasons"] = reasons
        if reasons:
            flagged.append(key)

    return {
        "baseline_facings": BASELINE_FACINGS,
        "baseline_ratio": round(baseline, 4),
        "ratio_tolerance": RATIO_TOLERANCE,
        "n_sprites": len(entries),
        "n_flagged": len(flagged),
        "flagged": sorted(flagged),
        "entries": entries,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--facing", nargs="*", default=None, help="restrict to these facing codes")
    parser.add_argument("--json", type=Path, default=None, help="also write full report to this path")
    parser.add_argument("--quiet", action="store_true", help="only print the summary, not every sprite")
    args = parser.parse_args(argv)

    facings_filter = set(args.facing) if args.facing else None
    if facings_filter and not facings_filter.issubset(_KNOWN_FACINGS):
        parser.error(f"unknown facing(s): {facings_filter - _KNOWN_FACINGS}")

    report = scan(facings_filter)

    print(f"baseline (mean head-ratio of top-row idle facings {report['baseline_facings']}): "
          f"{report['baseline_ratio']:.4f}")
    print(f"scanned {report['n_sprites']} sprites, {report['n_flagged']} flagged\n")

    if not args.quiet:
        for key in sorted(report["entries"]):
            e = report["entries"][key]
            if e.get("ratio") is None:
                print(f"  [ERR ] {key}: {e.get('error')}")
                continue
            mark = "FLAG" if e["flagged"] else "pass"
            print(f"  [{mark}] {key:32s} contract={e['contract']:7s} ratio={e['ratio']:.3f} "
                  f"skin_runs={e['skin_runs']} amber_px={e['amber_px']}"
                  + (f"  -- {'; '.join(e['flag_reasons'])}" if e["flagged"] else ""))

    if report["n_flagged"]:
        print(f"\nFLAGGED ({report['n_flagged']}): {', '.join(report['flagged'])}")

    if args.json:
        args.json.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
        print(f"\nfull report written to {args.json}")

    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
